resources:
- ../../base


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--enable-ssl-passthrough"
  target:
    kind: Deployment
    name: ingress-nginx-controller
- patch: |-
    - op: add
      path: /spec/loadBalancerIP
      value: 10.0.40.70
  target:
    kind: Service
    name: ingress-nginx-controller
- path: patch-tcp-services.yaml
