apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube-sonarqube
  namespace: sonarqube
spec:
  template:
    spec:
      containers:
        - name: sonarqube
          image: docker.io/sonarqube:9.9.5-community@sha256:11ddd66bdeee203327c444af17252075284a0b6b7db24e5aa1d3cd48eadd7681


