resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- target:
    kind: Deployment
    name: ingress-nginx-controller
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: "--enable-ssl-passthrough"

