apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-cache-volume
  namespace: trivy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  reclaimPolicy: Retain
