apiVersion: openclaw.rocks/v1alpha1
kind: OpenClawInstance
metadata:
  name: openclaw
  namespace: openclaw
spec:
  envFrom:
  - secretRef:
      name: openclaw-secrets
  config:
    raw:
      gateway:
        controlUi:
          allowedOrigins:
          - "http://openclaw.home"
          - "https://openclaw.home"
      agents:
        defaults:
          model:
            primary: "openrouter/qwen/qwen3-coder:free"
  storage:
    persistence:
      enabled: true
      size: 2Gi
      storageClass: longhorn
