apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  namespace: monitoring
  labels:
    team: frontend
    monitoring: "true"
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
