apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Setup
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.14/manifests/setup/namespace.yaml

# Prometheus Operator
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.77.1/bundle.yaml

# Alert Manager
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/alertmanager-alertmanager.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/alertmanager-networkPolicy.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/alertmanager-podDisruptionBudget.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/alertmanager-prometheusRule.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/alertmanager-secret.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/alertmanager-service.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/alertmanager-serviceAccount.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/alertmanager-serviceMonitor.yaml

# Grafana
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/grafana-config.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/grafana-dashboardDatasources.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/grafana-dashboardDefinitions.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/grafana-dashboardSources.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/grafana-deployment.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/grafana-prometheusRule.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/grafana-service.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/grafana-serviceAccount.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/grafana-serviceMonitor.yaml

- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubePrometheus-prometheusRule.yaml

# Kube State Metrics
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubeStateMetrics-clusterRole.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubeStateMetrics-clusterRoleBinding.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubeStateMetrics-deployment.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubeStateMetrics-networkPolicy.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubeStateMetrics-prometheusRule.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubeStateMetrics-service.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubeStateMetrics-serviceAccount.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubeStateMetrics-serviceMonitor.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubernetesControlPlane-prometheusRule.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubernetesControlPlane-serviceMonitorApiserver.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubernetesControlPlane-serviceMonitorCoreDNS.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubernetesControlPlane-serviceMonitorKubeControllerManager.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubernetesControlPlane-serviceMonitorKubeScheduler.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/kubernetesControlPlane-serviceMonitorKubelet.yaml 

# Node Exporter
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/nodeExporter-clusterRole.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/nodeExporter-clusterRoleBinding.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/nodeExporter-daemonset.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/nodeExporter-prometheusRule.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/nodeExporter-service.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/nodeExporter-serviceAccount.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/nodeExporter-serviceMonitor.yaml

# Prometheus
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheus-clusterRole.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheus-clusterRoleBinding.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheus-podDisruptionBudget.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheus-prometheus.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheus-prometheusRule.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheus-roleBindingConfig.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheus-roleBindingSpecificNamespaces.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheus-roleConfig.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheus-roleSpecificNamespaces.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheus-service.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheus-serviceAccount.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheus-serviceMonitor.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-apiService.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-clusterRole.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-clusterRoleAggregatedMetricsReader.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-clusterRoleBinding.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-clusterRoleBindingDelegator.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-clusterRoleServerResources.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-configMap.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-deployment.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-networkPolicy.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-podDisruptionBudget.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-roleBindingAuthReader.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-service.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-serviceAccount.yaml
- https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.14.0/manifests/prometheusAdapter-serviceMonitor.yaml


# Patch Prometheus to 1 replica
patches:
 - target:
      kind: Prometheus
      name: k8s
   path: prometheus-patch.yaml
# Patch Alert Manager to 1 replica
 - target:
      kind: Alertmanager
      name: main
   path: alertmanager-patch.yaml

