apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-homelab-instance
  namespace: awx
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  postgres_storage_class: "longhorn"
  postgres_data_volume_init: true
  projects_storage_class: "longhorn"
  projects_persistence: true

