apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus
resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- serviceaccount.yaml
- prometheus.yaml
- servicemonitor.yaml
- service.yaml
- https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/bundle.yaml
