apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: prometheus
spec:
  serviceAccountName: prometheus
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
  serviceMonitorSelector:
    matchExpressions:
      - {key: team, operator: In, values: [frontend]}
      - {key: prometheus, operator: In, values: [prometheus]}