apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    prometheus: prometheus
    monitoring: "true"
spec:
  selector:
    matchLabels:
      prometheus: prometheus
  endpoints:
  - port: web
    # path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  
