apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: prometheus
spec:
  selector:
    matchLabels:
      prometheus: prometheus
  endpoints:
  - port: web