apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sonarqube

helmCharts:
- name: sonarqube
  repo: https://SonarSource.github.io/helm-chart-sonarqube
  version: "~8" # Get the latest version in the 8.x series for Sonarqube 8 compatibility
  releaseName: sonarqube # The name you want to give to your Helm release
  namespace: sonarqube # The namespace to install into