apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: lb-test
spec:
  selector:
    matchLabels:
      appname: nginx-test
  replicas: 1
  template:
    metadata:
      labels:
        appname: nginx-test
    spec:
      containers:
      - name: my-nginx
        image: nginx@sha256:762ac2dbbd669a6e1e84cd189b85b95dde160a7262540fb6a9cf805e04c5b902
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0.1"
            memory: "256Mi"
          limits:
            cpu: "0.5"
            memory: "512Mi"
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 3000
          fsGroup: 2000
