apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: lb-test
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    appname: lb-test
  type: LoadBalancer
  loadBalancerIP: 10.0.3.61
