apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arc-systems
resources:
- ClusterRole.yaml
- ClusterRoleBinding.yaml
- Deployment.yaml
- Namespace.yaml
- Role.yaml
- RoleBinding.yaml
- ServiceAccount.yaml
- crd-autoscalinglisteners.yaml
- crd-autoscalingrunnersets.yaml
- crd-ephemeralrunners.yaml
- crd-ephemeralrunnersets.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/resources
      value: {}
  target:
    kind: Deployment
    name: arc-controller



